title: Godfred O. Anin # your name (or website title) here
logo: "/images/circle-cropped.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist  
  <br><br>
  Anything technology and football.I love Drake music
  <br><br>
  <a href="https://https://www.linkedin.com/in/godfred-osei-anin-261739193">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
