title: Anin O. Godfred # your name (or website title) here
logo: "/images/circle-cropped.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A tech enthusiast, passionate about new emerging technologies, and channeled my career towards data science. Occasional video gamer and pop music lover
  <br><br>
  I am available to work part-time or full-time and remotely. Get in touch!
  <br><br>
  <a href="https://https://www.linkedin.com/in/godfred-osei-anin-261739193">View My LinkedIn Profile</a> 
  


